Loading spinner
ericmguzmanc/egresados-uasd pull request #20
Opened 2023-10-08 22:48 UTC by elizonRL

![CargandoXdGIF](https://github.com/ericmguzmanc/egresados-uasd/assets/118481749/67ce5dfc-b1a7-451d-af9d-c08a20273dbe)
### Solucion al spinner provicional 
Este bug fue solucionado provicional mente usando un timer para mostrar el spinner al probar con la api deveriamos ver si usandolo sin el timer funcionaria

2023-10-08 22:58 UTC, elizonRL commented
comflicto resuelto

2023-10-09 13:17 UTC, ericmguzmanc commented on src/app/auth/login/login.page.ts
>              this.router.navigate(['/egresado-edit/', 1]);
umm deberíamos poner el `egresadoId` en el `router.navigate`, no el id 1, creo que ese bug lo introduje cuando puse el bug a funcionar inicialmente.

2023-10-09 13:17 UTC, ericmguzmanc commented on src/app/egresados/egresados.page.ts
> +          },1000)
Como ya estamos usando el mismo timeout en varios lugares, creo que deberíamos poner el tiempo en una constante. Puede ser en un archivo de constantes que hay en el `shared.module.ts`

puede ser algo así como `LOADING_SPINNER_TIMEOUT = 1000`, o algo así. De esta forma podemos modificar el tiempo del timeout en un solo lugar y el cambio iría para todo los loaders.

2023-10-09 13:17 UTC, ericmguzmanc commented on src/app/shared/components/egresados-list/egresados-list.component.html
> +            >
Remover los saltos de línea en este tag

2023-10-10 12:17 UTC, elizonRL commented on src/app/shared/components/egresados-list/egresados-list.component.html
> +            >
bien perfecto

2023-10-10 12:17 UTC, elizonRL commented on src/app/egresados/egresados.page.ts
> +          },1000)
lo pense, pero como es algo temporal queno se quedara en el codigo no lo hice

2023-10-10 12:28 UTC, elizonRL commented on src/app/shared/components/egresados-list/egresados-list.component.html
> +            >
corregido

2023-10-10 12:29 UTC, elizonRL commented on src/app/auth/login/login.page.ts
>              this.router.navigate(['/egresado-edit/', 1]);
sii, eso te iva a preguntar porque eso trae solo el egresado 1

2023-10-10 18:38 UTC, elizonRL commented
Cambios realizados base a comentarios

2023-10-11 00:45 UTC, ericmguzmanc requested changes
- [ ] Crear una variable en `contants.ts` para manejar el tiempo de timeout en los loaders. Esto hará que solo tengamos que declarar una sola vez la variable y podamos cambiar el tiempo de todos los loaders desde un solo lugar.

2023-10-11 00:45 UTC, ericmguzmanc commented on src/app/auth/login/login.page.ts
>              this.router.navigate(['/egresado-edit/', 1]);
Si, debemos redireccionar al egresado que se haya logeado

2023-10-11 00:45 UTC, ericmguzmanc commented on src/app/egresados/egresados.page.ts
> +          },1000)
aun así me parece que deberíamos hacerlo, por si las moscas si más adelante queremos probar la app y los loaders

2023-10-11 11:10 UTC, elizonRL commented
### Actalizado el branch 
ya cambia a la Constante `TIMER_LOANDING` en el archivo `constants.ts`

2023-10-11 12:36 UTC, ericmguzmanc approved these changes

2023-10-11 12:39 UTC, merged